import { Result } from 'neverthrow';
import { DomainError } from './errors.js';
import { ControllerId } from '../topology/ids.js';

export type ProvisioningStatus = 'active' | 'revoked';

export interface DeviceProvisioningRecord {
  readonly controllerId: ControllerId;
  readonly certificateThumbprint: string;
  readonly status: ProvisioningStatus;
  readonly provisionedAt: Date;
  readonly revokedAt?: Date | null;
}

export interface DeviceHeartbeatPayload {
  readonly controllerId: ControllerId;
  readonly appliedMatrixVersion: number;
  readonly firmwareVersion: string;
  readonly batteryStatus: 'ok' | 'low' | 'critical';
  readonly tamperState: boolean;
  readonly deviceTimestamp: number; // epoch ms
}

export interface RawControllerEventPayload {
  readonly eventId: string; // Stable UUID generated by controller before buffering
  readonly controllerId: ControllerId;
  readonly doorId: string;
  readonly eventType: string;
  readonly timestamp: string;
  readonly details?: Record<string, unknown>;
}

export interface IngestedEventResult {
  readonly eventId: string;
  readonly duplicate: boolean;
  readonly ingestedAt: Date;
}

export interface DeviceHealthStatus {
  readonly controllerId: ControllerId;
  readonly isOnline: boolean;
  readonly lastSeenAt: Date | null;
  readonly clockDriftMs: number; // difference in ms between server & device
  readonly clockDriftExceeded: boolean; // true if > 2000 ms
  readonly appliedMatrixVersion: number;
  readonly isMatrixUpToDate: boolean;
}

export interface DeviceGatewayPort {
  provisionDevice(controllerId: ControllerId, thumbprint: string): Result<DeviceProvisioningRecord, DomainError>;
  revokeCertificate(controllerId: ControllerId): Result<DeviceProvisioningRecord, DomainError>;
  ingestEvent(payload: RawControllerEventPayload): Result<IngestedEventResult, DomainError>;
  recordHeartbeat(payload: DeviceHeartbeatPayload, currentMatrixVersion: number, at?: Date): Result<DeviceHealthStatus, DomainError>;
}
